# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    pwd
    ls
    cat ./Southridge/dataset/VanCustomers.json
  displayName: 'Run a multi-line script'

- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'OTA-PRD-1436(a7df674c-6d40-4127-bb05-84b9c7600c7b)'
    ScriptType: 'InlineScript'
    Inline: |
      # You can write your azure powershell scripts inline here. 
      # You can also pass predefined and custom variables to this script using arguments
      Write-Output "Hello"
    azurePowerShellVersion: 'LatestVersion'
